### ISSUE TITLE
"ssg build" encounter error

### ISSUE THREAD

**Issue by luckypoem** [eunchan/website.code#1]
root@AR:/usr/local/www.eunchan.kim# .stack-work/dist/i386-linux/Cabal-1.24.0.0/build/ssg/ssg build
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  [ERROR] Hakyll.Core.Compiler.Require.load: _tpl/posts.html (snapshot _final) was not found in the cache, the cache might be corrupted or the item you are referring to might not exist
root@AR:/usr/local/www.eunchan.kim#

root@AR:/usr/local/www.eunchan.kim# ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
root@AR:/usr/local/www.eunchan.kim#

how to fix it?
thank you!

**Comment by eunchan** [comment]
Hi @luckypoem ,

Since that project contains only skeleton, you needs template files and also bunch of other post files to build up my site ;).

Those codes are maintained in private repository unfortunately.

Regards,
E. Kim

**Comment by luckypoem** [comment]
hi.
could u pls try https://github.com/aherrmann/aherrmann.github.io.hakyll ,try to install it on ur linux vps?
i always failed.
pls share ur setup experiences,if u are successful.

**Comment by eunchan** [comment]
Hi @luckypoem ,

I'm not using cabal as build system.
Trying with 'stack' has failed to find proper version for the library.

E.Kim
